### ISSUE TITLE
Create some code to test

### ISSUE THREAD

**Issue by BrunnoCD** [BrunnoCD/HellWorld#5]
- [x] Done when pull request is merged
- [x] Done when commit is done through CMD
- [x] Done when complete understand of git is reached.
